version: '3.8'

services:
  php:
    image: php:8.1-apache
    container_name: php-zentrotech
    volumes:
      - ./php:/var/www/html
    ports:
      - "8110:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
